name: diff_match_patch2
version: 0.5.0
description: Port of Google Diff, Match and Patch library to Dart
homepage: https://github.com/rikulo/diff-match-patch

dependencies:
  rikulo_commons: any

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: any
